#Connexion à la base de données 
spring.datasource.url=jdbc:sqlserver://localhost;databasename=BOOK_HUB;integratedSecurity=false;encrypt=false;trustServerCertificate=false 
spring.datasource.username=sa
spring.datasource.password=Root1234!

#Détail des requêtes pour le développement 
spring.jpa.show-sql=true 
spring.jpa.hibernate.ddl-auto=update