#Connexion à la base de données 
spring.datasource.url=jdbc:sqlserver://localhost;databasename=BOOK_HUB;integratedSecurity=false;encrypt=false;trustServerCertificate=false 
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd

#Détail des requêtes pour le développement 
spring.jpa.show-sql=true 
spring.jpa.hibernate.ddl-auto=update

#Configuration JWT
app.jwt.secret=mySecretKeyForBookHubApplicationThatIsAtleast32CharactersLongForHS256Algorithm
app.jwt.expiration=86400000

#Logging
logging.level.org.springframework.security=DEBUG